steps:
  # Reservations
  - name: 'gcr.io/cloud-builders/docker@sha256:13550fc742c667a6e8b130e708d89f2018b9cf500d0a21e3c336e4ede3fe111e'
    args:
      [
        'build',
        '-t',
        'us-east4-docker.pkg.dev/sleepr-407900/reservations/production',
        '-f',
        'apps/reservations/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker@sha256:13550fc742c667a6e8b130e708d89f2018b9cf500d0a21e3c336e4ede3fe111e'
    args:
      ['push','us-east4-docker.pkg.dev/sleepr-407900/reservations/production']
  # Auth
  - name: 'gcr.io/cloud-builders/docker@sha256:13550fc742c667a6e8b130e708d89f2018b9cf500d0a21e3c336e4ede3fe111e'
    args:
      [
        'build',
        '-t',
        'us-east4-docker.pkg.dev/sleepr-407900/auth/production',
        '-f',
        'apps/auth/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker@sha256:13550fc742c667a6e8b130e708d89f2018b9cf500d0a21e3c336e4ede3fe111e'
    args: ['push', 'us-east4-docker.pkg.dev/sleepr-407900/auth/production']
  # Notifications
  - name: 'gcr.io/cloud-builders/docker@sha256:13550fc742c667a6e8b130e708d89f2018b9cf500d0a21e3c336e4ede3fe111e'
    args:
      [
        'build',
        '-t',
        'us-east4-docker.pkg.dev/sleepr-407900/notifications/production',
        '-f',
        'apps/notifications/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker@sha256:13550fc742c667a6e8b130e708d89f2018b9cf500d0a21e3c336e4ede3fe111e'
    args: ['push','us-east4-docker.pkg.dev/sleepr-407900/notifications/production']
  # Payments
  - name: 'gcr.io/cloud-builders/docker@sha256:13550fc742c667a6e8b130e708d89f2018b9cf500d0a21e3c336e4ede3fe111e'
    args:
      [
        'build',
        '-t',
        'us-east4-docker.pkg.dev/sleepr-407900/payments/production',
        '-f',
        'apps/payments/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker@sha256:13550fc742c667a6e8b130e708d89f2018b9cf500d0a21e3c336e4ede3fe111e'
    args: ['push','us-east4-docker.pkg.dev/sleepr-407900/payments/production']